// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.22.3
// source: api/supervisor.proto

package gosv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRequest) Reset() {
	*x = ProcessRequest{}
	mi := &file_api_supervisor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRequest) ProtoMessage() {}

func (x *ProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_supervisor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRequest.ProtoReflect.Descriptor instead.
func (*ProcessRequest) Descriptor() ([]byte, []int) {
	return file_api_supervisor_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_api_supervisor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_supervisor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_supervisor_proto_rawDescGZIP(), []int{1}
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_api_supervisor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_supervisor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_api_supervisor_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ProcessStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Pid           int32                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	Restarts      int32                  `protobuf:"varint,4,opt,name=restarts,proto3" json:"restarts,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessStatus) Reset() {
	*x = ProcessStatus{}
	mi := &file_api_supervisor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessStatus) ProtoMessage() {}

func (x *ProcessStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_supervisor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessStatus.ProtoReflect.Descriptor instead.
func (*ProcessStatus) Descriptor() ([]byte, []int) {
	return file_api_supervisor_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessStatus) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessStatus) GetRestarts() int32 {
	if x != nil {
		return x.Restarts
	}
	return 0
}

func (x *ProcessStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processes     []*ProcessStatus       `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_supervisor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_supervisor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_supervisor_proto_rawDescGZIP(), []int{4}
}

func (x *StatusResponse) GetProcesses() []*ProcessStatus {
	if x != nil {
		return x.Processes
	}
	return nil
}

var File_api_supervisor_proto protoreflect.FileDescriptor

const file_api_supervisor_proto_rawDesc = "" +
	"\n" +
	"\x14api/supervisor.proto\x12\x04gosv\"$\n" +
	"\x0eProcessRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x0f\n" +
	"\rStatusRequest\">\n" +
	"\bResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x7f\n" +
	"\rProcessStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\x12\x1a\n" +
	"\brestarts\x18\x04 \x01(\x05R\brestarts\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"C\n" +
	"\x0eStatusResponse\x121\n" +
	"\tprocesses\x18\x01 \x03(\v2\x13.gosv.ProcessStatusR\tprocesses2\xef\x01\n" +
	"\n" +
	"Supervisor\x126\n" +
	"\fStartProcess\x12\x14.gosv.ProcessRequest\x1a\x0e.gosv.Response\"\x00\x125\n" +
	"\vStopProcess\x12\x14.gosv.ProcessRequest\x1a\x0e.gosv.Response\"\x00\x128\n" +
	"\x0eRestartProcess\x12\x14.gosv.ProcessRequest\x1a\x0e.gosv.Response\"\x00\x128\n" +
	"\tGetStatus\x12\x13.gosv.StatusRequest\x1a\x14.gosv.StatusResponse\"\x00B!Z\x1fgithub.com/kolkov/gosv/api/gosvb\x06proto3"

var (
	file_api_supervisor_proto_rawDescOnce sync.Once
	file_api_supervisor_proto_rawDescData []byte
)

func file_api_supervisor_proto_rawDescGZIP() []byte {
	file_api_supervisor_proto_rawDescOnce.Do(func() {
		file_api_supervisor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_supervisor_proto_rawDesc), len(file_api_supervisor_proto_rawDesc)))
	})
	return file_api_supervisor_proto_rawDescData
}

var file_api_supervisor_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_supervisor_proto_goTypes = []any{
	(*ProcessRequest)(nil), // 0: gosv.ProcessRequest
	(*StatusRequest)(nil),  // 1: gosv.StatusRequest
	(*Response)(nil),       // 2: gosv.Response
	(*ProcessStatus)(nil),  // 3: gosv.ProcessStatus
	(*StatusResponse)(nil), // 4: gosv.StatusResponse
}
var file_api_supervisor_proto_depIdxs = []int32{
	3, // 0: gosv.StatusResponse.processes:type_name -> gosv.ProcessStatus
	0, // 1: gosv.Supervisor.StartProcess:input_type -> gosv.ProcessRequest
	0, // 2: gosv.Supervisor.StopProcess:input_type -> gosv.ProcessRequest
	0, // 3: gosv.Supervisor.RestartProcess:input_type -> gosv.ProcessRequest
	1, // 4: gosv.Supervisor.GetStatus:input_type -> gosv.StatusRequest
	2, // 5: gosv.Supervisor.StartProcess:output_type -> gosv.Response
	2, // 6: gosv.Supervisor.StopProcess:output_type -> gosv.Response
	2, // 7: gosv.Supervisor.RestartProcess:output_type -> gosv.Response
	4, // 8: gosv.Supervisor.GetStatus:output_type -> gosv.StatusResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_supervisor_proto_init() }
func file_api_supervisor_proto_init() {
	if File_api_supervisor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_supervisor_proto_rawDesc), len(file_api_supervisor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_supervisor_proto_goTypes,
		DependencyIndexes: file_api_supervisor_proto_depIdxs,
		MessageInfos:      file_api_supervisor_proto_msgTypes,
	}.Build()
	File_api_supervisor_proto = out.File
	file_api_supervisor_proto_goTypes = nil
	file_api_supervisor_proto_depIdxs = nil
}
